// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhcvuEMPlSg2oub2riXX57LLCF0L_zpKY',
    appId: '1:368702408011:web:31c5eeecd68acf53f294ce',
    messagingSenderId: '368702408011',
    projectId: 'stvc-fcc83',
    authDomain: 'stvc-fcc83.firebaseapp.com',
    storageBucket: 'stvc-fcc83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXbovGqTbsnujftg-v0QOrltoCWVbU2oU',
    appId: '1:368702408011:android:d6328b6a37091457f294ce',
    messagingSenderId: '368702408011',
    projectId: 'stvc-fcc83',
    storageBucket: 'stvc-fcc83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFmFMrXPSb69Huimp_QY5ufuW2yps3KU',
    appId: '1:368702408011:ios:0c280b2c5b818559f294ce',
    messagingSenderId: '368702408011',
    projectId: 'stvc-fcc83',
    storageBucket: 'stvc-fcc83.firebasestorage.app',
    iosBundleId: 'com.example.stvcvibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXFmFMrXPSb69Huimp_QY5ufuW2yps3KU',
    appId: '1:368702408011:ios:0c280b2c5b818559f294ce',
    messagingSenderId: '368702408011',
    projectId: 'stvc-fcc83',
    storageBucket: 'stvc-fcc83.firebasestorage.app',
    iosBundleId: 'com.example.stvcvibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhcvuEMPlSg2oub2riXX57LLCF0L_zpKY',
    appId: '1:368702408011:web:634ce1ad70d61e10f294ce',
    messagingSenderId: '368702408011',
    projectId: 'stvc-fcc83',
    authDomain: 'stvc-fcc83.firebaseapp.com',
    storageBucket: 'stvc-fcc83.firebasestorage.app',
  );
}
